### ISSUE TITLE
Lockstep implementation

### ISSUE THREAD

**Issue by michalChrobot** [michalooo/Thesis-Deterministic-Lockstep-Netcode-DOTS-with-Validation#18]
**INFO**

- We are implementing basic lockstep where players are waiting for input from other players before progressing to the next frame, deterministic lockstep will be worked out later in the project
- Right now connection is based on TCP so we don't need to worry about jitter and buffers to solve that
- Every player is working with the same tickrate of **30**
- Project will start with new empty project with public packages
- We don't want to use N4E package for clearer implementation
- We should store the state of the simulation for debugging purposes (so in the future we could then brute force for determinism by rewinding + re-simulating and checking if hashed world match)
- Related articles that are explaining the subject 
https://gafferongames.com/post/deterministic_lockstep/
https://yal.cc/preparing-your-game-for-deterministic-netcode/
https://meseta.medium.com/netcode-concepts-part-3-lockstep-and-rollback-f70e9297271 

In our case the workflow should be that 
1. Clients are connecting to server and server sends them RPC to start the game (afterwards no connections are accepted)
2. Clients on frame 0 have info about all players with their ID and their cubes are instantiated with corresponding characterControllers
3. Client gets from the server info about players and tick
4. Client sends his input
5. Server after reciving all inputs sends all inputs combined to all clients together with corresponding tick
6. Client assignes inputs to approperiate characterControllers

- Denote that one client is the host.
- Host assigns ids for each player, like NetworkId in N4E.
- Host dictates game settings (like SimulationTickRate (60hz) and SimulationDelay (12 ticks = 200ms)).
- Once all players are connected, game starts.
    - Note that the driver needs to be kept alive. Transport may already handle this!
- New joiners will be ignored / kicked. They need to wait until the game ends + resets.
- First gameplay tick, spawn CCs for each player.

**"Host Timekeeping" Details** 
- When a client receives inputs for tick t (e.g. 155) AND is instructed to tick t (155), the client may simulate tick t (155).
    - This client is now supposed to send inputs for tick [t (155) + SimulationDelay (12)] = 167.
- When the host receives tick [>t] e.g. 156 from a player, it stores it in a buffer (e.g. of size 120 i.e. 2 seconds worth).
- When the host receives ALL inputs for tick 167, it'll forward them to all players, along with a tick delta to the currently simulated tick t (155).
- Once the host has ALL inputs for tick [t + 1] (156), AND 16.6ms has elapsed since it ticked frame 155, it'll tick simulation 156.
- Once a client has received this packet containing ALL inputs AND the tick delta (from the host), the client may use the delta to work out how long it should wait before ticking [t + 1] (156).

**System Groups**
- Fixed Simulation: Fetch Inputs -> Tick & Save N Times
- Render Simulation: Read Deterministic Simulation -> Update Presentation Entities with interpolation -> Render

**WHAT SHOULD I PAY ATTENTION TO**

- We will store my the world at every step. 1 world/tick copy
- order of queries can be indeterministic
- Prediction will have the most use for **fighting games**
- DOTS will have the most use for **RTS games**
- Host should act as a time keeper
- Getting Entities to be deterministic will likely be a huge challenge. But sorted ECB's (EntityCommandBuffers) is viable (but also quite slow).
- All inputs can have a base delay of 200ms, to have the buffer (from the server) describing what inputTicks can be send and what frames can be processed. For example then client know how many frames in advance can he send or maybe how many frames to resimulate

**QUESTIONS**

- What did they mean by separate worlds and self-contained environment
- GGPO / Client Prediction is not very common in RTS games, but necessary for (i.e. a requirement of) Fighting games. So what are we really proving?
- fixpoint library
- forced input latency

**SAVING WORLDS**

- 1000 worlds created at the beginning in circular buffer, when we will run out of space then exchange those at the beginning\
- We need another call regarding copying worlds (decision between copying whole worlds or only it's deterministic parts)

**PACKAGES INSTALLED**

- Entities (and dependencies), Transport
- Unity LTS 2022.3.13f1, 3d URP sample

**IMPLEMENTATION STEPS**

- [x]  Connect players via Transport package
- [x] When connecting to the host the tick rate is propagated
- [x] Gather properly player inputs in a struct
- [x] Send player inputs via transport
- [x] Implement same tick rate
- [x] Implement waiting for other player inputs
- [x] Implement progressing after recieving other inputs
- [x] Testing and description 
- [x] After building this solution, test it in the build with the console, right now is localhost
